/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToolsWaferOverlayRouteImport } from './routes/tools.wafer-overlay'
import { Route as ToolsTestPointAnalyzerRouteImport } from './routes/tools.test-point-analyzer'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsWaferOverlayRoute = ToolsWaferOverlayRouteImport.update({
  id: '/tools/wafer-overlay',
  path: '/tools/wafer-overlay',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsTestPointAnalyzerRoute = ToolsTestPointAnalyzerRouteImport.update({
  id: '/tools/test-point-analyzer',
  path: '/tools/test-point-analyzer',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/tools/test-point-analyzer': typeof ToolsTestPointAnalyzerRoute
  '/tools/wafer-overlay': typeof ToolsWaferOverlayRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/tools/test-point-analyzer': typeof ToolsTestPointAnalyzerRoute
  '/tools/wafer-overlay': typeof ToolsWaferOverlayRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/tools/test-point-analyzer': typeof ToolsTestPointAnalyzerRoute
  '/tools/wafer-overlay': typeof ToolsWaferOverlayRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/tools/test-point-analyzer' | '/tools/wafer-overlay'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/tools/test-point-analyzer' | '/tools/wafer-overlay'
  id: '__root__' | '/' | '/tools/test-point-analyzer' | '/tools/wafer-overlay'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ToolsTestPointAnalyzerRoute: typeof ToolsTestPointAnalyzerRoute
  ToolsWaferOverlayRoute: typeof ToolsWaferOverlayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/wafer-overlay': {
      id: '/tools/wafer-overlay'
      path: '/tools/wafer-overlay'
      fullPath: '/tools/wafer-overlay'
      preLoaderRoute: typeof ToolsWaferOverlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/test-point-analyzer': {
      id: '/tools/test-point-analyzer'
      path: '/tools/test-point-analyzer'
      fullPath: '/tools/test-point-analyzer'
      preLoaderRoute: typeof ToolsTestPointAnalyzerRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ToolsTestPointAnalyzerRoute: ToolsTestPointAnalyzerRoute,
  ToolsWaferOverlayRoute: ToolsWaferOverlayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
