// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SaveBase64Image(arg1, arg2) {
  return window['go']['main']['App']['SaveBase64Image'](arg1, arg2);
}

export function SaveWaferMapPNG(arg1) {
  return window['go']['main']['App']['SaveWaferMapPNG'](arg1);
}
